version: "3.7"
services:
  mqtt-broker:
    image: eclipse-mosquitto:1.6.4
    ports:
      - "1883:1883"
    volumes: 
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf" # Configure more logs
  rxpy-mqtt:
    build:
      context: .
    environment:
      - "MQTT_SERVICE=mqtt-broker"
    stdin_open: true
    tty: true
    command: 
      - "${app}"
    depends_on: 
      - mqtt-broker